=== Maksolo27/Hibernate_Homeworks/HW8/out/production/HW8/Tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="rootType"/>
  <xs:complexType name="TariffType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="Operator_name"/>
      <xs:element type="xs:string" name="payroll"/>
      <xs:element type="call_pricesType" name="call_prices"/>
      <xs:element type="xs:string" name="sms_price"/>
      <xs:element type="parametersType" name="parameters"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="TariffType" name="Tariff"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="call_pricesType">
    <xs:sequence>
      <xs:element type="xs:string" name="inside_net"/>
      <xs:element type="xs:string" name="outside_net"/>
      <xs:element type="xs:string" name="stationary"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="parametersType">
    <xs:sequence>
      <xs:element type="xs:string" name="custom_number"/>
      <xs:element type="xs:string" name="tarification"/>
      <xs:element type="xs:string" name="pay_for_tariff"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Maksolo27/Hibernate_Homeworks/HW8/src/Tariff.xml
<?xml version="1.0" encoding="UTF-8" ?>


<root xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation = "Tariff.xsd">

    <Tariff>
        <name>Lite</name>
        <Operator_name>Splunk</Operator_name>
        <payroll>20</payroll>
        <call_prices>
            <inside_net>200</inside_net>
            <outside_net>400</outside_net>
            <stationary>150</stationary>
        </call_prices>
        <sms_price>20</sms_price>
        <parameters>
            <custom_number>false</custom_number>
            <tarification>12</tarification>
            <pay_for_tariff>200</pay_for_tariff>
        </parameters>
    </Tariff>



</root>
